-- 코드를 입력하세요
SELECT T2.FOOD_TYPE FOOD_TYPE, T2.REST_ID REST_ID, T2.REST_NAME REST_NAME, T2.FAVORITES FAVORITES
FROM 
(SELECT FOOD_TYPE, max(favorites) AS FAVORITES from REST_INFO group by FOOD_TYPE) AS T1
JOIN 
REST_INFO AS T2
ON T1.FOOD_TYPE=T2.FOOD_TYPE AND T1.FAVORITES = T2.FAVORITES
ORDER BY FOOD_TYPE DESC;
