-- 코드를 입력하세요
SELECT USER.USER_ID, USER.NICKNAME, BOARD.PRICES AS TOTAL_SALES
FROM USED_GOODS_USER AS USER
JOIN
(SELECT WRITER_ID, SUM(PRICE) AS PRICES FROM USED_GOODS_BOARD WHERE STATUS='DONE' GROUP BY WRITER_ID HAVING PRICES >=700000) AS BOARD
ON USER.USER_ID = BOARD.WRITER_ID
ORDER BY TOTAL_SALES ASC;