-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, IFNULL(ROUND(AVG(R.REVIEW_SCORE),2),0.00) as SCORE 
FROM REST_INFO AS I RIGHT JOIN REST_REVIEW AS R ON I.REST_ID=R.REST_ID 
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE desc, I.FAVORITES DESC;