SELECT X.CAR_ID, IFNULL(Y.AVAILABILITY, "대여 가능") AS AVAILABILITY
FROM 
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) X
LEFT JOIN
(SELECT CAR_ID, "대여중" AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') Y
ON X.CAR_ID = Y.CAR_ID
GROUP BY X.CAR_ID
ORDER BY X.CAR_ID DESC;

