-- 코드를 입력하세요
SELECT X.AUTHOR_ID, X.AUTHOR_NAME, X.CATEGORY, SUM(X.PRICE * Y.SALES_SUM) AS TOTAL_SALES
FROM
(SELECT BOOK.BOOK_ID, BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, BOOK.PRICE
FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
) X
JOIN
(SELECT BOOK_ID, SUM(SALES) AS SALES_SUM FROM BOOK_SALES WHERE YEAR(SALES_DATE)='2022' AND MONTH(SALES_DATE)='01'
GROUP BY BOOK_ID) Y
ON X.BOOK_ID = Y.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;